### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by shanikadhettige** [GFDRR/community-mapping#106]
Hi @andresgnlez 
Could you please transfer ownership to https://github.com/GFDRR/community-mapping/ so that we can create get TransifexLive and create the CNAME from http://gfdrr.github.io/community-mapping/ or similar? I cannot do it as I am not admin here.

Thanks!
https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

**Comment by andresgnlez** [comment]
Hi Shanika, 

to transfer ownership I need admin rights in the Github account the repository is going to be transfered and the repository shouldn't exists (you have a fork of Vizzuality's one right now).

![image](https://cloud.githubusercontent.com/assets/999124/18701757/a6774650-7fde-11e6-83f9-f29b42616a67.png)

Could you please grant me permissions?

Thanks!

**Comment by shanikadhettige** [comment]
Let me know if you receive an invitation to be an owner on GFDRR now

**Comment by andresgnlez** [comment]
Not yet.

**Comment by andresgnlez** [comment]
I just received the invitation! I would need admin rights to complete the transference, could you please give me those permissions? Thanks so much.

**Comment by shanikadhettige** [comment]
You should have just received the owner request as well - let me know when
you've completed the transfer, thanks

**Comment by andresgnlez** [comment]
Yes, It's done! Community Mapping is already in GFDRR and live at http://gfdrr.github.io/community-mapping/ . I've granted you admin rights in the repository. This way you can add collaborators and do anything in the repository :)

Let me know if you have any problem!

Thanks!

**Comment by shanikadhettige** [comment]
Thanks much, @andresgnlez 

http://gfdrr.github.io/community-mapping/ works and we've now also redirected from https://opendri.org/community-mapping-guide
