### ISSUE TITLE
Update to new version

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/community-mapping#109]
From https://github.com/ppasq/community-mapping

Pending review and approval by @nualacowan and @gracedoherty

**Comment by gracedoherty** [comment]
Nuala, if we need to call to go over this let me know.

Small note: 
Strange that the index.html text for heading 1.1 is in Title Case, but on the site some of the words drop to lowercase:
![image](https://user-images.githubusercontent.com/42003495/57530742-e07f9880-7305-11e9-9427-832adbdb2500.png)

**Comment by ppasq** [comment]
@gracedoherty I think the title [should be this one](https://github.com/GFDRR/community-mapping/blob/gh-pages/index.html#L136).
In the new version [it is correct](https://ppasq.github.io/community-mapping/#introduction) but there could be others. We copied and pasted the translations so for any issue about the text please use Transifex

**Comment by ppasq** [comment]
Issue #113 must be solved before updating.

**Comment by ppasq** [comment]
The website has been updated so I'm closing this.
